// Copyright TheMonHub 2026.
// Distributed under the Boost Software License, Version 1.0.
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.

#ifndef KURO_CONF_H
#define KURO_CONF_H

#include <stdint.h>

#ifndef KURO_MAGIC
#define KURO_MAGIC {0x7F, 0x4B, 0x55, 0x52, 0x4F}
#endif

#ifndef KURO_MAGIC_LEN
#define KURO_MAGIC_LEN 5
#endif

typedef enum {
    KURO_LOG_LEVEL_NONE = 0,
    KURO_LOG_LEVEL_ERROR = 1,
    KURO_LOG_LEVEL_WARNING = 2,
    KURO_LOG_LEVEL_INFO = 3,
    KURO_LOG_LEVEL_DEBUG = 4
} KuroLogLevel;

typedef enum {
    KURO_CONFIG_VERSION_UNKNOWN = 0,
    KURO_CONFIG_VERSION_1 = 1,
} KuroConfigVersion;

typedef struct {
    char k_magic[KURO_MAGIC_LEN];
    uint8_t k_version;
    char k_reserved[2];
} KuroConfigIdentifier;

typedef struct {
    uint8_t secure_mode;
    uint8_t aslr_enabled;
    uint8_t public_key[32];
    uint8_t log_level;
    uint8_t console_log_level;
    uint32_t str_offset;
    KuroConfigIdentifier identifier;
} KuroConfig;

#endif //KURO_CONF_H